id = "wolfram"
name = "Wolfram Language"
version = "0.0.1"
schema_version = 1
authors = ["Riccardo Di Virgilio <riccardodivirgilio@gmail.com>"]
description = "Wolfram Language syntax highlighting for Zed, powered by tree-sitter-wolfram"
repository = "https://github.com/riccardodivirgilio/zed-wolfram"

[grammars.wolfram]
repository = "https://github.com/riccardodivirgilio/zed-wolfram-treesitter"
rev = "1a31279379b579faa2a35de246e7f3d2d1fc65a6"
